[package]
name = "satyananad/pgx-analyzer"
version = "2.0.0"
description = "Automated Population Pharmacogenomics Analysis Platform"

[app]
name = "pgx-analyzer"
owner = "satyananad"

[[command]]
name = "server"
runner = "https://webc.org/runner/wasi"

[deploy]
dockerfile = "Dockerfile"
